services:
  - type: web
    name: barbershop-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "https://james-barbery.vercel.app,http://localhost:5173,http://127.0.0.1:5173"
      - key: ADMIN_EMAIL
        sync: false
    # Keep service always running (no auto-sleep)
    autoDeploy: true
    healthCheckPath: /
    # Force CORS to allow Vercel frontend
