services:
  - type: web
    name: barbershop-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: ADMIN_EMAIL
        sync: false
    # Keep service always running (no auto-sleep)
    autoDeploy: true
    healthCheckPath: /api/health
